### ISSUE TITLE
win11 Running after installation does not respond

### ISSUE THREAD

**Issue by berry0131** [Macro-Deck-App/Macro-Deck#517]
Version 2.12 does not have access to the store，but2.13 Cannot be opened after installation

**Comment by manuelmayer-dev** [comment]
Please check if there is any error in the Windows event log.

**Comment by otavis** [comment]
me too
  AppName Macro Deck 2.exe 
  AppVersion 13.0.0.0 
  AppTimeStamp 65f90000 
  ModuleName KERNELBASE.dll 
  ModuleVersion 10.0.22621.3447 
  ModuleTimeStamp 3d876852 
  ExceptionCode e0434352 
  FaultingOffset 00000000000653ac 
  ProcessId 0x2d3c 
  ProcessCreationTime 0x1daa5b5951e2eae 
  AppPath D:\Macro Deck\Macro Deck 2.exe 
  ModulePath C:\Windows\System32\KERNELBASE.dll 
  IntegratorReportId ef8b9b5a-a142-4fcd-a4e8-d7bb3a0ad44b 
  PackageFullName  
  PackageRelativeAppId  

Application: Macro Deck 2.exe CoreCLR Version: 8.0.424.16909 .NET Version: 8.0.4 Description: The process was terminated due to an unhandled exception. Exception Info: System.TimeoutException: The operation has timed out. at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime) at SuchByte.MacroDeck.Pipes.MacroDeckPipeClient.SendPipeMessage(String message) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Pipe\MacroDeckPipeClient.cs:line 17 at SuchByte.MacroDeck.Pipes.MacroDeckPipeClient.SendShowMainWindowMessage() in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Pipe\MacroDeckPipeClient.cs:line 10 at SuchByte.MacroDeck.Program.CheckRunningInstance(Int32 ignoredPid) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Program.cs:line 38 at SuchByte.MacroDeck.Program.Main(String[] args) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\Program.cs:line 25

**Comment by mastervash** [comment]
I'm having crash on boot behavior on Win11 as well. I've pulled everything from Event Viewer, hoping that it can help. Look forward to trying out the project once it's back rockn and rolling! 

[Macro_Deck_Full_Event_List.txt](https://github.com/Macro-Deck-App/Macro-Deck/files/15307933/Macro_Deck_Full_Event_List.txt)
